[tool.poetry]
name = "BounceRL"
version = "0.0.41"
description = "Bounce RL"
authors = ["William Henning <wchenningwchenning@gmail.com>"]
readme = "README.md"
packages = [
    { include = "bounce_rl", from = "."},
]

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "^1.24.0"
gym = "0.23.1"
cffi = "^1.16.0"
simplejpeg = "^1.7.0"
psutil = "^5.9.8"
python-xlib = "^0.33"

[build-system]
requires = [
    "poetry-core>=1.2.1",
    "setuptools",
    "numpy",
    "cython",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "build.py"
generate-setup-file = true
